### ISSUE TITLE
Use /usr/share/tovid for scripts rather than /usr/lib/tovid

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#148]
_From [inetper...@gmail.com](https://code.google.com/u/108962948627171839167/) on April 30, 2011 09:39:40_

On Unix-like systems, /usr/lib is used for architecture-dependent files, and /usr/share for architecture-independent files. Since tovid scripts are architecture-independent, they should go to /usr/share.

_Original issue: http://code.google.com/p/tovid/issues/detail?id=148_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on July 09, 2011 00:43:04_

I agree.  However I do not feel up to taking on the python setup scripts.  If you or someone else wishes to contribute you can ask for commit status at freenode #tovid irc channel from wapcaplet.  (he is not there much so you might wish to PM him your email address).

Thanks for reporting.
grepper

**Comment by grepper** [comment]
This "bug" has been fixed in c74a525b (July, 2015). I am closing this issue.
