### ISSUE TITLE
Invoking ffmpeg with /dev/zero for input causes it to die from SIGFPE

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#150]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 01:04:00_

It seems that, when a silent menu is requested, tovid attempts to generate a silent audio file by invoking ffmpeg as:

ffmpeg -f s16le -i /dev/zero -ac 2 -ar 48000 -ab 224k -t 4 -acodec ac3 -y audio.ac3

This causes ffmpeg (tested with both 0.7.7 and 0.8.6) to die on start-up from SIGFPE, because it attempts to divide by zero. I reported the issue to ffmpeg ( https://ffmpeg.org/trac/ffmpeg/ticket/666 ), but tovid may need a different approach to reliably generating silence...

_Original issue: http://code.google.com/p/tovid/issues/detail?id=150_

**Comment by grepper** [comment]
_From [zzebs...@gmail.com](https://code.google.com/u/102596455105473816847/) on November 18, 2011 07:46:25_

FFMPEG 0.8  Floating point exception
line 779 in makemenu creating the 4 seconds of backgound audio the audio rate needs to be specified before the -f aswell as the current position in the command. eg 
CURRENT:

AUDIO_CMD="ffmpeg -f s16le -i /dev/zero -ac 2 -ar $SAMPRATE -ab 224k \
        $MENU_LENGTH -acodec $ASUF -y \"$AUDIO_STREAM\""

SHOULD BE:

AUDIO_CMD="ffmpeg -ar $SAMPRATE -f s16le -i /dev/zero -ac 2 -ar $SAMPRATE -ab 224k \
        $MENU_LENGTH -acodec $ASUF -y \"$AUDIO_STREAM\""

this fixs the issue of the floating point execption that occurs currently.
See ffmpeg ticket below http://ffmpeg.org/trac/ffmpeg/ticket/324#comment:4

**Comment by grepper** [comment]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 08:45:11_

Does `-ar $SAMPRATE' really needs to be specified twice for the work-around to work?

**Comment by grepper** [comment]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 14:01:03_

Here is the patch, which -- I think -- covers all occurrences, where ffmpeg is invoked with /dev/zero as argument.

**Attachment:** [patch-ffmpeg-zero](http://code.google.com/p/tovid/issues/detail?id=150#hc3)

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on November 27, 2011 18:13:30_

Thanks for the patch.  You should specify which version of tovid the patch is for - is it tovid-0.31 ?  I will be providing a patch for tovid-0.34 taken from SVN, where this workaround has already been implemented.  Thanks again for reporting, and please in future stick to current tovid version or SVN version for bug reports.  Patches for older versions can always be posted to the tovid-users mailing list.

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on November 27, 2011 22:52:49_

For users of current tovid: 0.34.  Here is the patch for this issue, affecting makemenu and makempg.  It was already added to todisc in this release, but didn't make it into these 2 scripts. https://code.google.com/p/tovid/downloads/detail?name=tovid-0.34_ffmpeg_silence.patch&can=2&q=

**Comment by grepper** [comment]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on December 01, 2011 16:27:12_

tovid-0.30 is the last version available on SourceForge (along with the patches-collection in tovid-0.30.2.patch.gz): http://heanet.dl.sourceforge.net/project/tovid/tovid/ If you moved the project out of SourceForge, perhaps, a note should be posted on the old location(s)...

**Comment by grepper** [comment]
Fixed. Closing.
