### ISSUE TITLE
sleep(1) takes numeric arguments ONLY

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#151]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 01:09:23_

The standard sleep(1) utility expects its argument as an integer number of seconds. Unfortunately, various tovid scripts append the letter "s" to the number.

Perhaps, this is acceptable on some obscure Operating Systems, but the redundant qualifier makes the scripts gratuitously unportable...

I'm attaching the (likely -- incomplete) patch, which fixes the problem.

_Original issue: http://code.google.com/p/tovid/issues/detail?id=151_

**Comment by grepper** [comment]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 13:59:03_

Here is an updated patch, which fixes a couple more occurrences.

**Attachment:** [patch-sleep](http://code.google.com/p/tovid/issues/detail?id=151#hc1)

**Comment by grepper** [comment]
These changes have been incorporated into tovid, closing with thanks.
