### ISSUE TITLE
df(1) invocation non-portable

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#152]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 12:58:59_

To estimate the amount of space left in the working directory, tovid invokes ``df -mP''. The -m is meant to request output in megabytes and the -P -- to get it in POSIX format.

This invocation is not very portable: for example, df(1M) on Solaris-10 does not have the -m flag at all, and only /usr/xpg4/bin/df (but not the /usr/bin/df) accept the -P.

On FreeBSD (and, likely, other BSD-systems), -P forces output to be in 512-byte blocks, although specifying -m after -P fixes that.

A simple fix would be to call df -Pm instead of -mP -- this would work on Linux and BSD, but still leave Solaris in the cold. A more complex fix would be to ensure, /usr/xpg4/bin is in the PATH ahead of /usr/bin and then use only the -P switch and perform the necessary computations in awk:

AVAIL_SPACE=$(df -P . | awk 'NR==1 {sub("-blocks", "", $2); blocksize=$2} NR!=1 {print int($4/1024*blocksize/1024)}')

_Original issue: http://code.google.com/p/tovid/issues/detail?id=152_

**Comment by grepper** [comment]
_From [virtuale...@gmail.com](https://code.google.com/u/108639885618215100917/) on November 18, 2011 14:00:14_

Here is the patch with the latter implementation.

**Attachment:** [patch-avail-space-df](http://code.google.com/p/tovid/issues/detail?id=152#hc1)

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on July 23, 2012 18:28:52_

The portable df line was changed in tovid svn r-3422 and will be part of tovid 0.35.
Thanks for the input.

**Status:** Accepted

**Comment by grepper** [comment]
Closed as the issue has been fixed.
