### ISSUE TITLE
seek not parsed properly from ini file or .bash into gui

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#158]
_From [sven.her...@gmail.com](https://code.google.com/u/107529408755939848526/) on January 06, 2012 03:11:01_

Example:

in ini-file (in [gui]:
-seek 400 400

is then displayed in the GUI as "4" "0" "0"

The same happens if you save the settings as a bash script and reload them.

Cheers,
Sven

_Original issue: http://code.google.com/p/tovid/issues/detail?id=158_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on January 09, 2012 21:40:36_

Thanks for taking the time to report.  At present the "Load script" function of the gui is very experimental as you found out.  There are a few other bugs that have been noted, in fact I filled out the issue report for some of them.  This report is similar to the note I added to issue `#121` .

Unfortunately the situation is not likely to improve unless we get another python dev willing to refactor the load_args method.

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on July 23, 2012 14:06:52_

As of SVN rev 3431 the 'Load script' button was removed from the GUI.  You can still save a project to a bash script with the 'Save script' button, so you won't lose your project details.  I will also have to make putting certain arguments/options (the problematic ones) in the ini file an error.  Not a fix, but at least no surprises.

**Comment by grepper** [comment]
Closing this issue as the situation was explained.
