### ISSUE TITLE
WARN: Partial sector read - ERR:  no VOBUs found

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#165]
_From [fhoug...@gmail.com](https://code.google.com/u/111401240262258223546/) on February 07, 2014 05:26:54_

﻿New to this forum.
 1. .mpg and .mp4 captured / downloaded in windows [xp sp3] do not seem to be editable in lubuntu [trim etc].
 2. tovid also seems to reject them. ﻿tovid dvd -author foo.xml > the process seems to hang when it gets to processing .mpg / .mp4 and rejects the process.
 any ideas?

What is a VOBU?

WARN: Partial sector read (1358 bytes); discarding data.
STAT: VOBU 0 at 0MB, 3 PGCs
ERR:  no VOBUs found.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
makedvd encountered an error during the DVD creation process:
Could not create the DVD-Video disc structure in final-dvd. Leaving final-dvd for inspection.

The above displayed at rejection.
frank

_Original issue: http://code.google.com/p/tovid/issues/detail?id=166_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on February 28, 2014 10:46:25_

Sorry, this is unclear. How did you convert this video to DVD compatible mpeg-2?
cheers,
grepper

**Status:** Questions

**Comment by grepper** [comment]
Closing this issue as there was no response.
