### ISSUE TITLE
idvid reports error "bash: Syntaxfehler beim unerwarteten Wort »(«"

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#167]
_From [heinz-ju...@arcor.de](https://code.google.com/u/114132917380257734471/) on July 09, 2014 12:11:15_

-- bash: syntaxerror at unexpected word "("

idvid -terse "$file"
ID_VIDEO_WIDTH=1920
ID_VIDEO_HEIGHT=1080
V_DURATION=9
ID_VIDEO_FPS=25.000
ID_VIDEO_FORMAT=H264
ID_AUDIO_CODEC=ffaac
ID_VIDEO_BITRATE=16305960
ID_AUDIO_BITRATE=254496
ID_AUDIO_NCH=2
ID_AUDIO_TRACKS=Stream,#0:1(eng):,Audio:,aac,(mp4a,/,0x6134706D),,48000,Hz,,stereo,,fltp,,254,kb/s
ID_VIDEO_TRACK=Stream
ID_AUDIO_IDS=0,,,,,,,,,,,,
ID_AUDIO_RATE=48000
V_ASPECT_WIDTH=177
ID_VIDEO_FRAMES=228

Its the line ID_AUDIO_TRACKS
The environment is set to
export LANG="en_EN.UTF-8"
export LC_NUMERIC=C
when delete the line from idvid-output:
eval `idvid -terse "$file" | grep -v 'ID_AUDIO_TRACKS'`
echo $?
0
everthing is fine.
The video file coms from a camcorder
 echo $file
/Video/118_0629/MVI_0193.MP4
Can someone direct me in the right direction.
Heinz-Jürgen

_Original issue: http://code.google.com/p/tovid/issues/detail?id=168_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on December 16, 2014 20:46:14_

ID_AUDIO_TRACKS should be something like:

ID_AUDIO_TRACKS=0:1

and ID_VIDEO_TRACKS something like:

ID_VIDEO_TRACK=0:2

(though usually audio is 0:2 and video 0:1)

I would guess you are using an old version of tovid and a much more recent ffmpeg or avconv. I suggest you upgrade to current tovid SVN if you haven't done so already.

**Owner:** grepper@gmail.com
